### ISSUE TITLE
output suggests ua apps but you need to ua enable esm-apps

### ISSUE THREAD

**Issue by mitechie** [canonical/sec-cvescan#47]
Working through the output I was hoping to bring it into alignment with at the end user needs to do to help mitigate something they find in the cvescan output. There's a disconnect in naming from the UA Apps vs the cli command 'ua enable esm-apps". 

However, as I started to perform the simple find/replace I see it gets more interesting as the "UA Apps" goes into the utc.json and the repository section there. I'm not sure where the best place to handle a transition from "back end" to user-facing might be.

**Comment by mssalvatore** [comment]
@mitechie, can you work with @lechsandecki to define what we want the output to say?

**Comment by mitechie** [comment]
Yes, I've spoken with him and we agree that the output should be ESM Apps, my question was where in the code was the safe place to flip that as changing it blows up the tests and I'm not sure the source of the utc.json file (UTC means a date to me so unclear if that's output from another tool that cannot be changed?)

**Comment by mssalvatore** [comment]
"uct.json" is Ubuntu CVE Tracker. That file name should probably change since we've started calling that json file the "ubuntu-vuln-db-RELEASE.json" file. 

Unfortunately, it's not a one line change due to a  failure to adequately use a constant on my part. In addition, that "UA Apps" string appears in that JSON file, which effectively leaks bits of the presentation layer into the data layer. This is my fault.

To further complicate matters, the mechanism for  deploying and updating of the JSON files is less than ideal. We're working on a solution, but as of yet we do not have a good devopsey way to fix the content in the JSON without breaking backwards compatibility.

In the short term, I can fix the use of constants and translate "UA Apps" to "ESM Apps" in the presentation layer. I can take care of it Monday.

**Comment by mssalvatore** [comment]
Presumably, we also want to translate "UA Infra" to "ESM Infra"? Doing these translations is a complete reversal of what I was told in June.

**Comment by mssalvatore** [comment]
@mitechie I've pushed a preliminary patch. It requires some more testing, if you'd like. Otherwise, I'll test it more thoroughly on Monday.

**Comment by mitechie** [comment]
Nice, thank you. It's a much cleaner path in that I was heading down.

**Comment by mssalvatore** [comment]
@mitechie this should now be fixed in the v2.4.0 snap which is available on the edge channel from the snap store.
