### ISSUE TITLE
Error: Failed to run oval scan 

### ISSUE THREAD

**Issue by philroche** [canonical/sec-cvescan#5]
I've run 

```
$ ./cvescan -v
Priority filter is 'high'
Running oval scan oscap oval eval --verbose WARNING --verbose-log-file debug.log --results results.xml com.ubuntu.eoan.cve.oval.xml (output logged to oval.log)
Error: Failed to run oval scan
```

I am running on Ubuntu 19.10 Eoan with oscap 1.2.16.

```
$ oscap -V
OpenSCAP command line tool (oscap) 1.2.16
Copyright 2009--2017 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1
CVRF Version: 1.1

==== Capabilities added by auto-loaded plugins ====
SCE Version: 1.0 (from libopenscap_sce.so.8)
```

See https://pastebin.ubuntu.com/p/tcv3Q2k35F/ for contents of oval.log.

What could be causing this?

**Comment by markmorlino** [comment]
To be honest, I have never tried to run under eoan. I believe that it should work though, at least for as long as eoan continues to be supported (and have oval files being produced for it).

Running as a snap, it will use the version of oscap that is installed in the snap rather than what is on your system.

I'll spin up an eoan VM and see if I can reproduce it

**Comment by philroche** [comment]
I saw the same with snap on eoan.

**Comment by philroche** [comment]
@mssalvatore I built openscap 1.3.2 from source and cvescan ran without issues. Thank you
